In [6]:
pip install numpy 

In [15]:
import numpy as np
arr = np.array([ 1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [12]:
import numpy as np
print(np.__version__)


2.1.3


In [14]:
import numpy as np 
arr = np.array([1,2,4,5,7,8])
print(arr)
print(type(arr))

[1 2 4 5 7 8]
<class 'numpy.ndarray'>


In [19]:
import numpy as np 
arr = np.array((1,2,4,5,7,8))
print(arr)

[1 2 4 5 7 8]


In [33]:
# 0 - D array 
import numpy as np 
arr = np.array(57)
print(arr)

57


In [21]:
# uni-dimensional or 1 - D array
import numpy as np 
arr = np.array([1,2,4,5,7,8])
print(arr)

[1 2 4 5 7 8]


In [24]:
# 2-D array
import numpy as np 
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [29]:
# 3-D array
import numpy as np
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
print(arr)

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]


In [32]:
# dimensional
import numpy as np
a = np.array(57)
b = np.array([1,2,4,5,7,8])
c = np.array([[1,2,3,4],[5,6,7,8]])
d = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [36]:
import numpy as np 
arr = np.array([1,2,3,4,5],ndmin = 5)
print(arr)
print('number of dimensional:',arr.ndim)

[[[[[1 2 3 4 5]]]]]
number of dimensional: 5


In [40]:
import numpy as np
arr = np.array([12,34,65,78,90],ndmin=7)
print(arr)
print('number of dimensional:',arr.ndim)

[[[[[[[12 34 65 78 90]]]]]]]
number of dimensional: 7


In [48]:
# indexing
import numpy as np
arr = np.array([12,34,54,56])
print(arr[2])


54


In [49]:
print(arr[0]+arr[1])

46


In [55]:
import numpy as np 
arr = np.array([[12,43,54,65,67], [43,45,56,67,68]])
print('4th element on 1st row : ',arr[0,3 ])

4nd element on 1st row :  65


In [56]:
print ('3rd element on 2nd row : ' , arr  [1,2])

3rd element on 2nd row :  56


In [63]:
import numpy as np 
arr = np.array([[12,43,54,65,67], [43,45,56,67,68]])
print('last element on 2nd dimensional :',arr[1,-1])

last element on 2nd dimensional : 68


In [1]:
import numpy as np
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
print(arr[0,1,2])

7


In [2]:
#slicing array 
import numpy as np 
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:3])

[2 3]


In [3]:
print(arr[1:])

[2 3 4 5 6 7 8 9]


In [4]:
print(arr[:2])

[1 2]


In [5]:
print(arr[4:])

[5 6 7 8 9]


In [7]:
print(arr[:4])

[1 2 3 4]


In [10]:
#negative slicing
import numpy as np
arr = ([1,2,3,4,5,6,7,9,8])
print(arr[-5:-2])

[5, 6, 7]


In [11]:
print(arr[-2:])

[9, 8]


In [16]:
print(arr[1:5:2])

[2, 4]


In [17]:
print(arr[::2])

[1, 3, 5, 7, 8]


In [18]:
# slicing 2D
import numpy as np
arr = np.array([[42,43,44,45],[46,47,48,49]])
print(arr[1,1:4])

[47 48 49]


In [22]:
print(arr[0:2,3])

[45 49]


In [26]:
print(arr[0:2,1:3])

[[43 44]
 [47 48]]
